name: alh_pdf_view
description: Has the functionality to show PDF with bytes of a file path as widget with some extra functionalities.
version: 2.3.0
repository: https://github.com/alhappler/alh_pdf_view

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: alh_pdf_view_android
      ios:
        default_package: alh_pdf_view_ios

dependencies:
  flutter:
    sdk: flutter
  alh_pdf_view_android: ^2.2.0
  alh_pdf_view_ios: ^2.2.0
  alh_pdf_view_platform_interface: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  plugin_platform_interface: ^2.0.2
  stream_transform: ^2.1.0

  mocktail: ^1.0.3

topics:
  - pdf
  - pdf-flutter
